### ISSUE TITLE
Будет ли работать с 8.2?

### ISSUE THREAD

**Issue by wolfktl** [bessonovevgen/srv-1c-linux-zabbix-template#1]
Будет ли работать с 8.2? если подправить пути сервера?

**Comment by pumbaEO** [comment]
Нет, в 8.2 нет утилиты rac/ras

**Comment by bessonovevgen** [comment]
> Нет, в 8.2 нет утилиты rac/ras
> Память подводит, но кажется видел на ИТС в документации по 8.2 видел упоминания про утилиты, но теперь найти не могу.
