### ISSUE TITLE
Не поддерживается

### ISSUE THREAD

**Issue by DishinIR** [bessonovevgen/srv-1c-linux-zabbix-template#17]
Подскажите пож-та все сделал по инструкции Zabbix пишет что не поддерживается и дает ошибку Value "???।???????? ??????: |." of type "string" is not suitable for value type "Numeric (unsigned)" В каком направлении искать проблему?

**Comment by bessonovevgen** [comment]
Привет.
1. Что возвращает "rac session --cluster=<uuid> list --infobase=<uuid> |  find /c "1CV8C""?
2. Что вощвращает zabbix_get?

Исходя из этого дальше смотреть что к чему.

**Comment by DishinIR** [comment]
я в этом деле пока новичок, подскажите где это смотреть?

**Comment by DishinIR** [comment]
Проблема решена, разобрались. Спасибо.

**Comment by bessonovevgen** [comment]
Было бы здорово, если бы, в двух словах, написали в чем была проблема.

**Comment by nkolodin** [comment]
> Было бы здорово, если бы, в двух словах, написали в чем была проблема.

Проблема заключается в неправильном указании uuid основных параметров.
