### ISSUE TITLE
Будет ли реализация под windows?

### ISSUE THREAD

**Issue by wolfktl** [bessonovevgen/srv-1c-linux-zabbix-template#2]
Будет ли реализация под windows?

**Comment by bessonovevgen** [comment]
Для запуска сервера администрирования под windows на ИТС-е есть пример скрипта, не уверен что можно сюда оттуда копипастить.

Шаблон изменений не требует, нужно только в UserParameters прописать пути до исполняемого файла rac.

**Comment by wolfktl** [comment]
Скинь его суда

**Comment by dlebedev** [comment]
Запустил сервер под VMWare Player и агент на виндовом сервере родной. Спасибо, очень помогли ваши инструкции.

**Comment by bessonovevgen** [comment]
> Спасибо, очень помогли ваши инструкции.
> На здоровье.
