### ISSUE TITLE
Администратор кластер

### ISSUE THREAD

**Issue by zuriy** [bessonovevgen/srv-1c-linux-zabbix-template#3]
В строке rac стоит наверно указать --cluster-user=zabbix --cluster-pwd=pw
Вроде как должны работать авторизация виндовая для пользователя, который запускает Zabbix-agent, но у меня получилось отправить данные только после явного указания логина\пароля.

**Comment by bessonovevgen** [comment]
Да, естественно, если задан создан администратор кластера, то для аутентификации нужно указывать.

Касаемо авторизации - не уверен. Для надежности лучше передавать параметрами.
