### ISSUE TITLE
Не работает получение регламентных заданий в Windows

### ISSUE THREAD

**Issue by zuriy** [bessonovevgen/srv-1c-linux-zabbix-template#5]
Я долго не могу понять почему у меня кол-во регламентных заданий 0. Хотя они запускались. 
У вас закралась ошибка, лишний пробел: 
UserParameter=onec-bgj,"C:\Program Files\1cv8\8.3.9.1850\bin\rac.exe" session --cluster=<uuid> list --infobase=<uuid> | find /c **"BackgroundJob "**
После исключения проблема, все заработало.

**Comment by bessonovevgen** [comment]
Спасибо. Поправил.
